### ISSUE TITLE
change MySQL timestamp to JST

### ISSUE THREAD

**Issue by nshun583** [nshun583/my-first-rails#21]

**Comment by nshun583** [comment]
* MySQL record
```
mysql> select * from my_first_rails_development.articles;
+----+-------+--------------------+----------------------------+----------------------------+--------+
| id | title | body               | created_at                 | updated_at                 | status |
+----+-------+--------------------+----------------------------+----------------------------+--------+
|  3 | test  | article_from_mysql | 2022-11-04 12:43:14.286030 | 2022-11-04 12:43:14.286030 | public |
+----+-------+--------------------+----------------------------+----------------------------+--------+
1 row in set (0.00 sec)
```

* log/development.log
```
Started POST "/articles" for 127.0.0.1 at 2022-11-04 21:43:14 +0900
Processing by ArticlesController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "article"=>{"title"=>"test", "body"=>"article_from_mysql", "status"=>"public"}, "commit"=>"Create Article"}
  TRANSACTION (0.2ms)  BEGIN
  ↳ app/controllers/articles_controller.rb:19:in `create'
  Article Create (0.4ms)  INSERT INTO `articles` (`title`, `body`, `created_at`, `updated_at`, `status`) VALUES ('test', 'article_from_mysql', '2022-11-04 12:43:14.286030', '2022-11-04 12:43:14.286030', 'public')
  ↳ app/controllers/articles_controller.rb:19:in `create'
  TRANSACTION (9.4ms)  COMMIT
  ↳ app/controllers/articles_controller.rb:19:in `create'
Redirected to http://127.0.0.1:3000/articles/3
Completed 302 Found in 23ms (ActiveRecord: 10.0ms | Allocations: 4050)
```

**Comment by nshun583** [comment]
* OS timezone

```
$ timedatectl status
               Local time: 土 2022-11-05 17:15:10 JST
           Universal time: 土 2022-11-05 08:15:10 UTC
                 RTC time: 土 2022-11-05 08:15:10
                Time zone: Asia/Tokyo (JST, +0900)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

* MySQL timezone

```
mysql> show variables like '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | JST    |
| time_zone        | SYSTEM |
+------------------+--------+
2 rows in set (0.07 sec)
```

* MySQL now()

```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2022-11-05 17:16:36 |
+---------------------+
1 row in set (0.00 sec)
```
=> ActiveRecord issue?

**Comment by nshun583** [comment]
* timezone in Rails
  * config.time_zone / https://guides.rubyonrails.org/configuring.html#config-time-zone
     * `Sets the default time zone for the application and enables time zone awareness for Active Record.`
     * https://guides.rubyonrails.org/configuring.html#initializers
        * `active_support.initialize_time_zone: Sets the default time zone for the application based on the config.time_zone setting, which defaults to "UTC". `
   * config.active_record.default_timezone / https://guides.rubyonrails.org/configuring.html#config-active-record-default-timezone 
     * `Determines whether to use Time.local (if set to :local) or Time.utc (if set to :utc) when pulling dates and times from the database. The default is :utc.`
 * **Conclusion**
   * this is the way it is in Rails for ActiveRecord date records insertion / reading
   * is customizable, but do not feel the needs to do so for now
