### ISSUE TITLE
support soft(logical) delete in articles/comments

### ISSUE THREAD

**Issue by nshun583** [nshun583/my-first-rails#23]
https://github.com/jhawthorn/discard

**Comment by nshun583** [comment]
* generate migration for adding the needed column

```
$ bin/rails generate migration AddDiscardedAtToArticles discarded_at:datetime:index
      invoke  active_record
      create    db/migrate/20221105100342_add_discarded_at_to_articles.rb
$ bin/rails generate migration AddDiscardedAtToComments discarded_at:datetime:index
      invoke  active_record
      create    db/migrate/20221105100403_add_discarded_at_to_comments.rb
```

* migrate

```
$ bin/rails db:migrate
== 20221105100342 AddDiscardedAtToArticles: migrating =========================
-- add_column(:articles, :discarded_at, :datetime)
   -> 0.4222s
-- add_index(:articles, :discarded_at)
   -> 0.2107s
== 20221105100342 AddDiscardedAtToArticles: migrated (0.6333s) ================

== 20221105100403 AddDiscardedAtToComments: migrating =========================
-- add_column(:comments, :discarded_at, :datetime)
   -> 0.1094s
-- add_index(:comments, :discarded_at)
   -> 0.1878s
== 20221105100403 AddDiscardedAtToComments: migrated (0.2998s) ================
```

* confirm

```
mysql> desc my_first_rails_development.articles;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | bigint       | NO   | PRI | NULL    | auto_increment |
| title        | varchar(255) | YES  |     | NULL    |                |
| body         | text         | YES  |     | NULL    |                |
| created_at   | datetime(6)  | NO   |     | NULL    |                |
| updated_at   | datetime(6)  | NO   |     | NULL    |                |
| status       | varchar(255) | YES  |     | NULL    |                |
| discarded_at | datetime(6)  | YES  | MUL | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)

mysql> desc my_first_rails_development.comments;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | bigint       | NO   | PRI | NULL    | auto_increment |
| commenter    | varchar(255) | YES  |     | NULL    |                |
| body         | text         | YES  |     | NULL    |                |
| article_id   | bigint       | NO   | MUL | NULL    |                |
| created_at   | datetime(6)  | NO   |     | NULL    |                |
| updated_at   | datetime(6)  | NO   |     | NULL    |                |
| status       | varchar(255) | YES  |     | NULL    |                |
| discarded_at | datetime(6)  | YES  | MUL | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+
8 rows in set (0.01 sec)
```

**Comment by nshun583** [comment]
* test / delete article 

```
mysql> select * from my_first_rails_development.articles;
+----+-------+-------------------+----------------------------+----------------------------+--------+--------------+
| id | title | body              | created_at                 | updated_at                 | status | discarded_at |
+----+-------+-------------------+----------------------------+----------------------------+--------+--------------+
|  1 | test  | test test test    | 2022-11-05 10:41:46.856007 | 2022-11-05 10:41:46.856007 | public | NULL         |
|  2 | test2 | test2 test2 test2 | 2022-11-05 10:42:05.198191 | 2022-11-05 10:42:05.198191 | public | NULL         |
+----+-------+-------------------+----------------------------+----------------------------+--------+--------------+
2 rows in set (0.00 sec)
```

```
Started DELETE "/articles/2" for 127.0.0.1 at 2022-11-05 19:58:55 +0900
Processing by ArticlesController#destroy as TURBO_STREAM
  Parameters: {"id"=>"2"}
  Article Load (1.1ms)  SELECT `articles`.* FROM `articles` WHERE `articles`.`discarded_at` IS NULL AND `articles`.`id` = 2 LIMIT 1
  ↳ app/controllers/articles_controller.rb:41:in `destroy'
  TRANSACTION (0.2ms)  BEGIN
  ↳ app/controllers/articles_controller.rb:42:in `destroy'
  Article Update (2.8ms)  UPDATE `articles` SET `articles`.`updated_at` = '2022-11-05 10:58:55.384145', `articles`.`discarded_at` = '2022-11-05 10:58:55.383660' WHERE `articles`.`id` = 2
  ↳ app/controllers/articles_controller.rb:42:in `destroy'
  TRANSACTION (11.0ms)  COMMIT
  ↳ app/controllers/articles_controller.rb:42:in `destroy'
Redirected to http://127.0.0.1:3000/
Completed 303 See Other in 41ms (ActiveRecord: 15.1ms | Allocations: 3275)
```

```
mysql> select * from my_first_rails_development.articles;
+----+-------+-------------------+----------------------------+----------------------------+--------+----------------------------+
| id | title | body              | created_at                 | updated_at                 | status | discarded_at               |
+----+-------+-------------------+----------------------------+----------------------------+--------+----------------------------+
|  1 | test  | test test test    | 2022-11-05 10:41:46.856007 | 2022-11-05 10:41:46.856007 | public | NULL                       |
|  2 | test2 | test2 test2 test2 | 2022-11-05 10:42:05.198191 | 2022-11-05 10:58:55.384145 | public | 2022-11-05 10:58:55.383660 |
+----+-------+-------------------+----------------------------+----------------------------+--------+----------------------------+
2 rows in set (0.00 sec)
```

**Comment by nshun583** [comment]
* test / delete comment

```
mysql> select * from my_first_rails_development.comments;
+----+-----------+-------+------------+----------------------------+----------------------------+--------+--------------+
| id | commenter | body  | article_id | created_at                 | updated_at                 | status | discarded_at |
+----+-----------+-------+------------+----------------------------+----------------------------+--------+--------------+
|  1 | test      | test  |          1 | 2022-11-05 10:43:23.541819 | 2022-11-05 10:43:23.541819 | public | NULL         |
|  2 | test2     | test2 |          1 | 2022-11-05 10:43:39.005954 | 2022-11-05 10:43:39.005954 | public | NULL         |
+----+-----------+-------+------------+----------------------------+----------------------------+--------+--------------+
2 rows in set (0.00 sec)
```

```
Started DELETE "/articles/1/comments/2" for 127.0.0.1 at 2022-11-05 20:03:01 +0900
Processing by CommentsController#destroy as TURBO_STREAM
  Parameters: {"article_id"=>"1", "id"=>"2"}
  Article Load (0.3ms)  SELECT `articles`.* FROM `articles` WHERE `articles`.`discarded_at` IS NULL AND `articles`.`id` = 1 LIMIT 1
  ↳ app/controllers/comments_controller.rb:11:in `destroy'
  Comment Load (0.5ms)  SELECT `comments`.* FROM `comments` WHERE `comments`.`article_id` = 1 AND `comments`.`id` = 2 LIMIT 1
  ↳ app/controllers/comments_controller.rb:12:in `destroy'
  TRANSACTION (0.2ms)  BEGIN
  ↳ app/controllers/comments_controller.rb:13:in `destroy'
  Comment Update (3.1ms)  UPDATE `comments` SET `comments`.`updated_at` = '2022-11-05 11:03:01.172107', `comments`.`discarded_at` = '2022-11-05 11:03:01.167909' WHERE `comments`.`id` = 2
  ↳ app/controllers/comments_controller.rb:13:in `destroy'
  TRANSACTION (8.8ms)  COMMIT
  ↳ app/controllers/comments_controller.rb:13:in `destroy'
Redirected to http://127.0.0.1:3000/articles/1
Completed 303 See Other in 43ms (ActiveRecord: 13.0ms | Allocations: 4122)
```

```
mysql> select * from my_first_rails_development.comments;
+----+-----------+-------+------------+----------------------------+----------------------------+--------+----------------------------+
| id | commenter | body  | article_id | created_at                 | updated_at                 | status | discarded_at               |
+----+-----------+-------+------------+----------------------------+----------------------------+--------+----------------------------+
|  1 | test      | test  |          1 | 2022-11-05 10:43:23.541819 | 2022-11-05 10:43:23.541819 | public | NULL                       |
|  2 | test2     | test2 |          1 | 2022-11-05 10:43:39.005954 | 2022-11-05 11:03:01.172107 | public | 2022-11-05 11:03:01.167909 |
+----+-----------+-------+------------+----------------------------+----------------------------+--------+----------------------------+
2 rows in set (0.00 sec)
```

```

Started GET "/articles/1" for 127.0.0.1 at 2022-11-05 20:03:01 +0900
Processing by ArticlesController#show as TURBO_STREAM
  Parameters: {"id"=>"1"}
  Article Load (0.6ms)  SELECT `articles`.* FROM `articles` WHERE `articles`.`discarded_at` IS NULL AND `articles`.`id` = 1 LIMIT 1
  ↳ app/controllers/articles_controller.rb:9:in `show'
  Rendering layout layouts/application.html.erb
  Rendering articles/show.html.erb within layouts/application
  Comment Load (0.4ms)  SELECT `comments`.* FROM `comments` WHERE `comments`.`article_id` = 1 AND `comments`.`discarded_at` IS NULL
  ↳ app/views/articles/show.html.erb:14
  Rendered collection of comments/_comment.html.erb [1 times] (Duration: 1.1ms | Allocations: 142)
  Rendered comments/_form.html.erb (Duration: 2.5ms | Allocations: 1422)
  Rendered articles/show.html.erb within layouts/application (Duration: 14.7ms | Allocations: 2701)
  Rendered layout layouts/application.html.erb (Duration: 19.7ms | Allocations: 4986)
Completed 200 OK in 40ms (Views: 24.2ms | ActiveRecord: 1.0ms | Allocations: 5964)
```
