### ISSUE TITLE
"ActiveRecord::InvalidForeignKey (SQLite3::ConstraintException: FOREIGN KEY constraint failed):" in DELETE

### ISSUE THREAD

**Issue by nshun583** [nshun583/my-first-rails#9]
```
Started DELETE "/articles/4" for 127.0.0.1 at 2022-11-03 22:42:52 +0900
Processing by ArticlesController#destroy as TURBO_STREAM
  Parameters: {"id"=>"4"}
  Article Load (0.1ms)  SELECT "articles".* FROM "articles" WHERE "articles"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
  ↳ app/controllers/articles_controller.rb:39:in `destroy'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/articles_controller.rb:40:in `destroy'
  Article Destroy (1.1ms)  DELETE FROM "articles" WHERE "articles"."id" = ?  [["id", 4]]
  ↳ app/controllers/articles_controller.rb:40:in `destroy'
  TRANSACTION (0.2ms)  rollback transaction
  ↳ app/controllers/articles_controller.rb:40:in `destroy'
Completed 500 Internal Server Error in 28ms (ActiveRecord: 1.4ms | Allocations: 3064)
  
ActiveRecord::InvalidForeignKey (SQLite3::ConstraintException: FOREIGN KEY constraint failed):
  
app/controllers/articles_controller.rb:40:in `destroy'
```

**Comment by nshun583** [comment]
fixed by setting model relationship
https://guides.rubyonrails.org/association_basics.html#dependent
